"""binfmt_misc registration for transparent .exe execution."""

from __future__ import annotations

import os
import shlex
import shutil
import stat
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from winbox.config import Config

BINFMT_NAME = "winbox"
BINFMT_PROC = Path("/proc/sys/fs/binfmt_misc")
BINFMT_ENTRY = BINFMT_PROC / BINFMT_NAME
BINFMT_PERSIST = Path("/etc/binfmt.d/winbox.conf")

HANDLER_TEMPLATE = """\
#!/bin/bash
# winbox binfmt_misc handler — do not edit, regenerated by: winbox binfmt enable

EXE_PATH="$1"
shift

WINBOX={winbox_path}
TOOLS_DIR={tools_dir}

EXE_NAME="$(basename "$EXE_PATH")"

# If exe is NOT in tools dir, copy it there so it's accessible via VirtIO-FS
if [ "$(dirname "$(realpath "$EXE_PATH")")" != "$(realpath "$TOOLS_DIR")" ]; then
    cp "$EXE_PATH" "$TOOLS_DIR/$EXE_NAME" || {{ echo "winbox: failed to copy $EXE_PATH to $TOOLS_DIR" >&2; exit 1; }}
fi

exec "$WINBOX" exec "$EXE_NAME" "$@"
"""


def generate_handler(cfg: Config) -> str:
    """Generate handler script content with hardcoded paths."""
    winbox_path = shutil.which("winbox")
    if winbox_path is None:
        raise FileNotFoundError("winbox not found on PATH")
    return HANDLER_TEMPLATE.format(
        winbox_path=shlex.quote(winbox_path),
        tools_dir=shlex.quote(str(cfg.tools_dir)),
    )


def install_handler(cfg: Config) -> Path:
    """Write handler script to ~/.winbox/binfmt-handler.sh and make executable."""
    handler = cfg.winbox_dir / "binfmt-handler.sh"
    handler.write_text(generate_handler(cfg))
    handler.chmod(handler.stat().st_mode | stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
    return handler


def registration_string(handler_path: Path) -> str:
    """Build the binfmt_misc registration string."""
    return f":{BINFMT_NAME}:E::exe::{handler_path}:"


def register(cfg: Config, persist: bool = True) -> Path:
    """Register .exe handler via binfmt_misc. Returns handler path.

    Unregisters first if already registered. Optionally writes
    /etc/binfmt.d/winbox.conf for reboot persistence.
    """
    if not BINFMT_PROC.exists():
        raise RuntimeError(
            "binfmt_misc not mounted. Run: sudo mount -t binfmt_misc none /proc/sys/fs/binfmt_misc"
        )

    if is_registered():
        unregister(remove_handler=False)

    handler_path = install_handler(cfg)
    reg_str = registration_string(handler_path)

    _sudo_write(BINFMT_PROC / "register", reg_str)

    if persist:
        _sudo_write(BINFMT_PERSIST, reg_str + "\n")

    return handler_path


def unregister(remove_handler: bool = True) -> None:
    """Unregister .exe handler and optionally remove persistent config."""
    if is_registered():
        _sudo_write(BINFMT_ENTRY, "-1")

    if remove_handler and BINFMT_PERSIST.exists():
        subprocess.run(
            ["sudo", "rm", "-f", str(BINFMT_PERSIST)],
            check=True,
        )


def is_registered() -> bool:
    """Check if winbox binfmt entry exists."""
    return BINFMT_ENTRY.exists()


def mark_tools_executable(cfg: Config) -> int:
    """Set +x on all .exe files in tools dir. Returns count."""
    count = 0
    if not cfg.tools_dir.exists():
        return count
    for f in cfg.tools_dir.iterdir():
        if f.is_file() and f.name.lower().endswith(".exe"):
            mode = f.stat().st_mode
            if not (mode & stat.S_IXUSR):
                f.chmod(mode | stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
                count += 1
    return count


def handler_path(cfg: Config) -> Path:
    """Return the expected handler script path."""
    return cfg.winbox_dir / "binfmt-handler.sh"


def _sudo_write(path: Path, content: str) -> None:
    """Write content to path via sudo tee."""
    result = subprocess.run(
        ["sudo", "tee", str(path)],
        input=content.encode(),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        detail = result.stderr.decode().strip() if result.stderr else "sudo denied?"
        raise PermissionError(f"Failed to write to {path}: {detail}")
